"""empty message

Revision ID: c7763e47915b
Revises: 4f49926ab9b6
Create Date: 2022-09-12 19:55:20.032158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7763e47915b'
down_revision = '4f49926ab9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_products',
    sa.Column('cart', sa.Integer(), nullable=True),
    sa.Column('product_price', sa.Numeric(), nullable=True),
    sa.Column('product_items', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cart'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['product_items'], ['product.items'], ),
    sa.ForeignKeyConstraint(['product_price'], ['product.price'], )
    )
    op.drop_table('order')
    op.drop_table('courier')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'price')
    op.drop_column('cart', 'items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('items', sa.VARCHAR(), nullable=True))
    op.add_column('cart', sa.Column('price', sa.NUMERIC(), nullable=True))
    op.create_foreign_key(None, 'cart', 'product', ['price'], ['price'])
    op.create_foreign_key(None, 'cart', 'product', ['items'], ['items'])
    op.create_table('courier',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=25), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data_created', sa.DATETIME(), nullable=False),
    sa.Column('items', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['items'], ['product.items'], ),
    sa.ForeignKeyConstraint(['price'], ['product.price'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cart_products')
    # ### end Alembic commands ###
